### ISSUE TITLE
demo does not run in Google colab

### ISSUE THREAD

**Issue by Duxon** [microscopic-image-analysis/bayes-mef#2] opened 2024-03-25 11:39 UTC
When running the demo code in Colab using the provided link, I encounter the following error in the first code block:

```
--> 328         return list(public_symbols)
    329 
    330     # Pytest testing

AttributeError: module 'numpy' has no attribute 'typing'
```

This suggests a potential issue with the Numpy version installed in this environment. numpy.typing was introduced in Numpy version 1.20. The demo code runs well locally with numpy 1.24. on my machine.

**Comment by ShantanuKodgirwar** [comment] 2024-03-25 16:22
Thanks for letting me know Jacob! The issue was the importing of `np.typing`. The numpy versions are ensured to be  >=1.22 . 

I made some changes and hopefully the issue is now fixed. Although, I do see some installation issues that depend on some colab version. Although, running the first cell twice does the job. Feel free to try it out again.

**Closed as completed by ShantanuKodgirwar** 2024-03-25 16:22 UTC
